openapi: 3.0.3
info:
  title: ChivoSpot API
  version: 1.0.0
  description: API para descubrimiento y gestión de eventos en El Salvador.
servers:
  - url: https://api.chivospot.sv
  - url: http://localhost:4000/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        titulo:
          type: string
        descripcion:
          type: string
        fecha_inicio:
          type: string
          format: date-time
        fecha_fin:
          type: string
          format: date-time
        precio:
          type: number
        estado_publicacion:
          type: string
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        user:
          type: object
paths:
  /auth/register:
    post:
      summary: Registro de usuarios organizadores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, nombre]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                nombre:
                  type: string
      responses:
        '201':
          description: Usuario creado
  /auth/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Token de acceso emitido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /auth/me:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil del usuario
  /departments:
    get:
      summary: Listado de departamentos
      responses:
        '200':
          description: Lista
  /departments/{id}/municipalities:
    get:
      summary: Municipios por departamento
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Lista de municipios
  /categories:
    get:
      summary: Listado de categorías
      responses:
        '200':
          description: OK
  /events:
    get:
      summary: Buscar eventos
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: department_id
          schema:
            type: integer
        - in: query
          name: municipality_id
          schema:
            type: integer
        - in: query
          name: category_id
          schema:
            type: array
            items:
              type: integer
        - in: query
          name: bbox
          schema:
            type: string
        - in: query
          name: order
          schema:
            type: string
      responses:
        '200':
          description: Resultados
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
  /events/{id}:
    get:
      summary: Obtener evento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Evento
  /events/{id}/favorite:
    post:
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Marcado como favorito
    delete:
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Eliminado
  /org/events:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Eventos del organizador
  /admin/events:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Bandeja de moderación
  /analytics:
    post:
      summary: Registrar evento analítico
      responses:
        '202':
          description: Aceptado
security:
  - bearerAuth: []
